[project]
name = "bayesian-statistics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arviz>=0.22.0",
    "matplotlib>=3.10.3",
    "numba>=0.61.2",
    "pymc>=5.25.0",
    "pytensor>=2.31.7",
]
